type="webpack"
account_id=""
zone_id=""
route=""
usage_model=""
compatibility_flags=[]
workers_dev=false
site={bucket="./dist", entry-point="workers-site"}
compatibility_date="2021-10-22"

[env.dev]
name="dev_stokilo_com"
route="dev.stokilo.com/*"
workers_dev=false

[env.prod]
name="prod_stokilo_com"
route="stokilo.com/*"
workers_dev=false
